services:
  postgres:
    image: postgres:15
    container_name: ga4_postgres
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: pocpass
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: ga4_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
